// ─────────────────────────────────────────────
// data.js — Local Cricket Teams & Players
// ─────────────────────────────────────────────

export const TEAMS_DATA = [
  { id: 'aj',   name: 'Addalu Javaner',             shortName: 'AJ',   color: '#004BA0', textColor: '#ffffff', purse: 100000, owner: 'Prashanth Acharya',  iconPlayer: 'Akshay Acharya' },
  { id: 'bfcl', name: 'B.F.C Legends',              shortName: 'BFCL', color: '#FFCB05', textColor: '#1a1a1a', purse: 100000, owner: 'Suraj Shetty',       iconPlayer: 'Deepak Hegde' },
  { id: 'bfc',  name: 'B.F.C',                      shortName: 'BFC',  color: '#D4213D', textColor: '#ffffff', purse: 100000, owner: 'Deekshith Hegde',    iconPlayer: 'Sunil Shetty' },
  { id: 'ysc',  name: 'Yuva Sanghama Cricketers',   shortName: 'YSC',  color: '#3A225D', textColor: '#ffffff', purse: 100000, owner: 'Suresh',             iconPlayer: 'Santhosh' },
  { id: 'dfc',  name: 'D.F.C Nakre',                shortName: 'DFC',  color: '#10b981', textColor: '#ffffff', purse: 100000, owner: 'Nitesh',             iconPlayer: 'Rakesh' },
  { id: 'nen',  name: 'New Eleven Nakre',            shortName: 'NEN',  color: '#FF822A', textColor: '#ffffff', purse: 100000, owner: 'Ajay',               iconPlayer: 'Prajwal' },
  { id: 'smcn', name: 'S.M.C.N',                    shortName: 'SMCN', color: '#EA1A85', textColor: '#ffffff', purse: 100000, owner: 'Suresh',             iconPlayer: 'Sri Ram' },
  { id: 'mc',   name: 'Maheshwara Cricketers',      shortName: 'MC',   color: '#0078BC', textColor: '#ffffff', purse: 100000, owner: 'Rakshan',            iconPlayer: 'Rakshith (Chippi)' },
];

export const PLAYERS_DATA = [
  // ── Batsmen (17) ──────────────────────────────
  { id: 1,  name: 'Adarsh Nakre',         role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'N/A',       isWK: false, image: 'images/Adarsh Nakre.jpg', ,
  { id: 2,  name: 'Arjun Acharya',        role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Arjun Acharya.jpg', ,
  { id: 3,  name: 'Atheeth Kumar',         role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Atheeth Kumar.jpg', ,
  { id: 4,  name: 'Deekshith Acharya',    role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Deekshith Acharya.jpg', ,
  { id: 5,  name: 'Dinesh Nakre',          role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Dinesh Nakre.jpg', ,
  { id: 6,  name: 'Kaushik',              role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'N/A',       isWK: false, image: 'images/Kaushik.jpg', ,
  { id: 7,  name: 'Keshava',              role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Keshava.jpg', ,
  { id: 8,  name: 'Kiran IK',             role: 'Batsman',     location: 'Others',      batting: 'Right Hand', bowling: 'N/A',       isWK: false, image: 'images/Kiran Ik.jpg', ,
  { id: 9,  name: 'Krapal Dsouza',        role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Krapal Dsouza.jpg', ,
  { id: 10, name: 'Manish IK',            role: 'Batsman',     location: 'Others',      batting: 'Right Hand', bowling: 'N/A',       isWK: false, image: 'images/Manish IK.jpg', ,
  { id: 11, name: 'Nithin IK',            role: 'Batsman',     location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Nithin IK.jpg', ,
  { id: 12, name: 'Prashanth Putthu',     role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Prashanth Putthu.jpg', ,
  { id: 13, name: 'Praveen Kumar',        role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'N/A',       isWK: false, image: 'images/Praveen Kumar.jpg', ,
  { id: 14, name: 'Rajesh Pollu',         role: 'Batsman',     location: 'Parapu',      batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Rajesh Pollu.jpg', ,
  { id: 15, name: 'Sandeep Bandary',      role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/SANDEEP BANDARY.jpg', ,
  { id: 16, name: 'Shashi IK',            role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Shashi IK.jpg', ,
  { id: 17, name: 'Vighnesh Kotian',      role: 'Batsman',     location: 'Nakre',       batting: 'Right Hand', bowling: 'N/A',       isWK: false, image: 'images/Vighnesh Kottian.jpg', ,

  // ── Bowlers (8) ───────────────────────────────
  { id: 18, name: 'Manish',               role: 'Bowler',      location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Manish.jpg', ,
  { id: 19, name: 'Manish DFC',           role: 'Bowler',      location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, basePrice: 1000 },
  { id: 20, name: 'Prakash Kenchal',      role: 'Bowler',      location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Prakash Kenchal.jpg', ,
  { id: 21, name: 'Ranjan',               role: 'Bowler',      location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Ranjan.jpg', ,
  { id: 22, name: 'Santhosh Kumar',       role: 'Bowler',      location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Santosh Kumar.jpg', ,
  { id: 23, name: 'Sujith Manigudde',     role: 'Bowler',      location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Sujith Manigudde.jpg', ,
  { id: 24, name: 'Suresh DFC',           role: 'Bowler',      location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Suresh DFC.jpg', ,
  { id: 25, name: 'Vasanth',              role: 'Bowler',      location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Vasanth.jpg', ,

  // ── All-Rounders (60) ─────────────────────────
  { id: 26, name: 'Abhishek',             role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Abhishek.jpg', ,
  { id: 27, name: 'Adarsh Acharya',       role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Adarsh Acharya.jpg', ,
  { id: 28, name: 'Adarsh Salian',        role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Adarsh Salian.jpg', ,
  { id: 29, name: 'Adithya MJ',           role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Adithya MJ.jpg', ,
  { id: 30, name: 'Ajay',                 role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Ajay.jpg', ,
  { id: 31, name: 'Ajith Acharya',        role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Ajith Acharya.jpg', ,
  { id: 32, name: 'Ajith',                role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Ajith.jpg', ,
  { id: 33, name: 'Akshath Acharya',      role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Aksasth Acharya.jpg', ,
  { id: 34, name: 'Arun Shetty',          role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Arun Shetty.jpg', ,
  { id: 35, name: 'Ashwath',              role: 'All-Rounder', location: 'Nakre Padav', batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Ashwath.jpg', ,
  { id: 36, name: 'Charan IK',            role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Charan IK.jpg', ,
  { id: 37, name: 'Deepu IK',             role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Deepu Ik.jpg', ,
  { id: 38, name: 'Deeraj Hegde',         role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Deeraj Hegde.jpg', ,
  { id: 39, name: 'Dinesh',               role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Dinesh.jpg', ,
  { id: 40, name: 'Ganesh Acharya',       role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Ganesh Acharya.jpg', ,
  { id: 41, name: 'Ganesh Ponnedaguri',   role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, basePrice: 1000 },
  { id: 42, name: 'Girish Posanottu',     role: 'All-Rounder', location: 'Nakre',       batting: 'Left Hand',  bowling: 'Left Arm',  isWK: false, image: 'images/Girish Posanottu.jpg', ,
  { id: 43, name: 'Harish Shetty',        role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Harish Shetty.jpg', ,
  { id: 44, name: 'Harshith',             role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Harshith.jpg', ,
  { id: 45, name: 'Jags Shetty',          role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Jags Shetty.jpg', ,
  { id: 46, name: 'Jais',                 role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Jais.jpg', ,
  { id: 47, name: 'Jeevan Shetty',        role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Jeevan Shetty.jpg', ,
  { id: 48, name: 'Karthik Rao',          role: 'All-Rounder', location: 'Nakre Padav', batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Karthik Rao.jpg', ,
  { id: 49, name: 'Kishan',               role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Kishan.jpg', ,
  { id: 50, name: 'Nagesh Posanottu',     role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Nagesh Posanottu.jpg', ,
  { id: 51, name: 'Nagu Parapu',          role: 'All-Rounder', location: 'Parapu',      batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Nagu Parapu.jpg', ,
  { id: 52, name: 'Nikil Shetty',         role: 'All-Rounder', location: 'Parapu',      batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Nikil Shetty.jpg', ,
  { id: 53, name: 'Nithin Shetty',        role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Nithin Shetty.jpg', ,
  { id: 54, name: 'Pradeep',              role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'N/A',       isWK: false, image: 'images/Pradeep.jpg', ,
  { id: 55, name: 'Prashanth',            role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Prashanth.jpg', ,
  { id: 56, name: 'Praveen',              role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Praveen.jpg', ,
  { id: 57, name: 'Preetham',             role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Preetham.jpg', ,
  { id: 58, name: 'Rakesh Pakku',         role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Rakesh Pakku.jpg', ,
  { id: 59, name: 'Rakshith Poojary',     role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Rakshtih Poojary.jpg', ,
  { id: 60, name: 'Rakshith',             role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Rakshith.jpg', ,
  { id: 61, name: 'Ramesh',               role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Ramesh.jpg', ,
  { id: 62, name: 'Royson IK',            role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Royson IK.jpg', ,
  { id: 63, name: 'Samanth',              role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Samanth.jpg', ,
  { id: 64, name: 'Samith',               role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Samith.jpg', ,
  { id: 65, name: 'Sandeep Munna',        role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Sandeep Munna.jpg', ,
  { id: 66, name: 'Sandesh IK',           role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Sandesh Ik.jpg', ,
  { id: 67, name: 'Sanjeeva Naik',        role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Sanjeev Naik.jpg', ,
  { id: 68, name: 'Santhosh IK',          role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Santhosh IK.jpg', ,
  { id: 69, name: 'Santhosh Manigudde',   role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Santhosh Manigudde.jpg', ,
  { id: 70, name: 'Santhosh Mendis',      role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Santhosh Mendis.jpg', ,
  { id: 71, name: 'Sathish',              role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Sathish.jpg', ,
  { id: 72, name: 'Shailu',               role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Shailu.jpg', ,
  { id: 73, name: 'Sharath',              role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Sharath.jpg', ,
  { id: 74, name: 'Shreyas B Acharya',    role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Shreayas B Acharaya.jpg', ,
  { id: 75, name: 'Sudhakara Sacchu',     role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Sudhakara Sacchu.jpg', ,
  { id: 76, name: 'Sujith',               role: 'All-Rounder', location: 'Nakre',       batting: 'Left Hand',  bowling: 'Left Arm',  isWK: false, image: 'images/Sujith.jpg', ,
  { id: 77, name: 'Sukesh Shetty',        role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Sukesh Shetty.jpg', ,
  { id: 78, name: 'Sukesh Padav',         role: 'All-Rounder', location: 'Nakre Padav', batting: 'Left Hand',  bowling: 'Left Arm',  isWK: false, image: 'images/Sukesh Padav.jpg', ,
  { id: 79, name: 'Sukesh Posanottu',     role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Sukesh Posanottu.jpg', ,
  { id: 80, name: 'Sunil IK',             role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Sunil IK.jpg', ,
  { id: 81, name: 'Suresh Chikka',        role: 'All-Rounder', location: 'Nakre',       batting: 'Left Hand',  bowling: 'Left Arm',  isWK: false, image: 'images/Suresh Chikka.jpg', ,
  { id: 82, name: 'Swasthi IK',           role: 'All-Rounder', location: 'Others',      batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Swasthi Ik.jpg', ,
  { id: 83, name: 'Umesh',                role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Umesh.jpg', ,
  { id: 84, name: 'Vijay',                role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: true,  image: 'images/Vijay.jpg', ,
  { id: 85, name: 'Vittal Manigudde',     role: 'All-Rounder', location: 'Nakre',       batting: 'Right Hand', bowling: 'Right Arm', isWK: false, image: 'images/Vittal Manigudde.jpg', ,
];

// Role display config
export const ROLE_CONFIG = {
  'Batsman':     { icon: '🏏', color: '#3b82f6' },
  'Bowler':      { icon: '🎯', color: '#ef4444' },
  'All-Rounder': { icon: '⭐', color: '#f59e0b' },
};

// Location display config
export const LOCATION_CONFIG = {
  'Nakre':       { icon: '📍' },
  'Nakre Padav': { icon: '📍' },
  'Parapu':      { icon: '📍' },
  'Others':      { icon: '📍' },
};
